#!/bin/sh

set -e

PREREQ="btrfs"

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

if [ -x /sbin/btrfs ]
then
	timestamp=$(date +%Y%m%d-%H%M%S%z)
	mkdir -p /mnt/btrfs
	for uuid in $(btrfs filesystem show | grep ^Label | awk '{print $4}'); do
		mount /dev/disk/by-uuid/$uuid /mnt/btrfs
		cd /mnt/btrfs
		if [ ! -d snapshots ];then
			mkdir snapshots
		fi
		for subvol in $(btrfs subvolume list . | grep -v / | grep -v DELETED | awk '{n = split($0, a); print a[n]}'); do
			snapshot_name=$(echo $subvol | sed -r 's/^\@(.*)/\1/')
			if [ -z $snapshot_name ]; then
				snapshot_name=root
			fi
			btrfs subvolume snapshot -r $subvol snapshots/$snapshot_name@$timestamp
		done
		cd $OLDPWD
		umount /mnt/btrfs
	done
fi

exit 0
